version: "3"

services:
#  db:
#    image: mysql
#    volumes:
#      - ./dockerMysql:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rmsdnr96@@
#      MYSQL_DATABASE: test
  app:
    build: .
#    depends_on:
#      - db
    ports:
      - "8080:8080"