version: "3"

services:
  db:
    image: mysql
    container_name: test_db
    volumes:
      - ./dockerMysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testLocalMysql
      - MYSQL_ROOT_HOST:%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/testLocalMysql?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234