version: "3.9"
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: kakaodb
      ## 데이터베이스 credential 생략
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
    command:
      - --default-time-zone=Asia/Seoul
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
