version: "3"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=kakaodb 
      - MYSQL_ROOT_PASSWORD=root
    healthcheck: # mysql 사용 가능한지 확인
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  kakaocafe:
    image: kakaocafe:0.0.1
    depends_on: # mysql-item에서 mysql 실행된 후 실행
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"