version: "3"

services:
  app:
    depends_on:
      - db
    image: jiyolla/kakaocafe
    ports:
      - "9000:8080"
    environment:
      DB_HOST: jdbc:mysql://db
      DB_PORT: 3306
      DB_NAME: kakaocafe_db
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kakaocafe_db

    volumes:
      - ~/home/be-w34-spring-cafe/mysqldb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
