version: "3.9"

services:
  api_server:
    image: api_server
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    restart: always
    image: mysql
    platform: linux/x86_64
    container_name: database
    ports:
      - "3306:3306"
    env_file: ./.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
