# May use extends https://docs.docker.com/compose/extends/
# However, that complicates Docker compose file.

version: '3.0'
services:
  cafe_server:
    image: jindomin/cafe-server:1.0.0
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - '8080:8080'
    environment:
      DEPLOY: "dev"
    depends_on:
      - mysql

  mysql:
    image: jindomin/mysql:1.0.0
    build:
      context: .
      dockerfile: DockerfileDatabase
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "kakao"
      MYSQL_PASSWORD: "kakao"
      MYSQL_DATABASE: "kakaodb"
#    volumes:
#      - /tmp/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping' ]
      interval: 3s
      timeout: 1s
      retries: 10
