CREATE TABLE IF NOT EXISTS USER_INFO (
    ID INTEGER AUTO_INCREMENT,
    EMAIL VARCHAR(30),
    NAME VARCHAR(30),
    PASSWORD VARCHAR(30),
    CREATION_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    ID INTEGER AUTO_INCREMENT,
    WRITER VARCHAR(30),
    TITLE VARCHAR(255),
    CONTENT TEXT,
    CREATION_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
