DROP TABLE REPLY IF EXISTS;
DROP TABLE ARTICLE IF EXISTS;
DROP TABLE USER IF EXISTS;

CREATE TABLE USER
(
    id         BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    uid        VARCHAR(15) NOT NULL UNIQUE,
    password   VARCHAR(15) NOT NULL,
    name       VARCHAR(10) NOT NULL,
    email      VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE ARTICLE
(
    id         BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    uid        VARCHAR(15)  NOT NULL,
    title      VARCHAR(255) NOT NULL,
    body       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES USER (uid) ON DELETE CASCADE
);

CREATE TABLE REPLY
(
    id         BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    article_id BIGINT       NOT NULL,
    uid        VARCHAR(15)  NOT NULL,
    user_name  VARCHAR(10)  NOT NULL,
    body       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (article_id) REFERENCES ARTICLE (id) ON DELETE CASCADE,
    FOREIGN KEY (uid) REFERENCES USER (uid) ON DELETE CASCADE
);
