DROP TABLE IF EXISTS users;
CREATE TABLE users (
    email VARCHAR(100) PRIMARY KEY,
    nick_name VARCHAR (100) NOT NULL,
    summary VARCHAR (255) NOT NULL,
    profile VARCHAR (255) NOT NULL,
    password VARCHAR (100) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
