POST http://localhost:8080/users
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"

frank
--WebAppBoundary
Content-Disposition: form-data; name="password"

password
--WebAppBoundary
Content-Disposition: form-data; name="email"

frank@example.com

###
