DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS POSTS;

CREATE TABLE USERS
(
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    userId VARCHAR(10) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(30) NOT NULL
);

CREATE TABLE POSTS
(
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    writerId UUID NOT NULL,
    title CHAR(100) NOT NULL,
    content CLOB NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (writerId) REFERENCES USERS(id)
);
