DROP TABLE users if EXISTS;
CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255),
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    created_time TIMESTAMP,
    PRIMARY KEY(id)
);


DROP TABLE articles IF EXISTS;
CREATE TABLE articles
(
    id BIGINT NOT NULL AUTO_INCREMENT,
    writer_name VARCHAR(255),
    title VARCHAR(255),
    contents VARCHAR(255),
    created_time TIMESTAMP,
    is_deleted BOOLEAN NOT NULL default false,
    user_id BIGINT NOT NULL,
    CONSTRAINT `ARTICLE_PK` PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

DROP TABLE comments IF EXISTS;
CREATE TABLE IF NOT EXISTS `comments`
(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `writer_name` VARCHAR(255),
    `contents` VARCHAR(5000),
    `created_time` TIMESTAMP,
    `is_deleted` BOOLEAN NOT NULL default false,
    `user_id` BIGINT NOT NULL,
    `article_id` BIGINT NOT NULL,
    CONSTRAINT `COMMENT_PK` PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES USERS (`id`),
    FOREIGN KEY (`article_id`) REFERENCES ARTICLES (`id`)
);
