DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS POSTS;

CREATE TABLE USERS
(
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    userId VARCHAR(10) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(30) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE POSTS
(
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    writerId CHAR(36) NOT NULL,
    title CHAR(100) NOT NULL,
    content TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP DEFAULT NULL,
    deleted BOOLEAN DEFAULT FALSE
);
