spring:
  mustache:
    cache: 'false'
    suffix: .html
    expose-session-attributes: true
  datasource:
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      tracking-modes: cookie
