spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mustache:
    cache: false
    expose-session-attributes: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb
  h2:
    console:
      enabled: true
      path: /h2-console
