spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

handlebars:
  suffix: .html
  cache: false

server:
  servlet:
    session:
      tracking-modes: cookie
