spring:
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true
  datasource:
    url: jdbc:mysql://localhost:3306/kakaodb
    username: root
    password: password
server:
  servlet:
    session:
      tracking-modes: cookie