spring:
  thymeleaf:
    cache: false
    view-names: ['*']
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafe
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true