spring:
  mustache:
    cache: false
    suffix: .html
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kakaodb
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
