spring:
  config:
    import: vault://secret/2022-kakao-newkrew-tech-onboarding-test/test/datasource

  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true

  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  cloud:
    vault:
      host: vault-beta.daumkakao.io
      port: 443
      authentication: approle
      app-role:
        role-id: foo #credentials
        secret-id: bar #credentials
      fail-fast: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}

management:
  health:
    refresh:
      enabled: false

server:
  servlet:
    session:
      tracking-modes: cookie
