spring:
  mustache:
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

server:
  error:
    whitelabel:
      enabled: false
    path: /error