spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe

  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

server:
  servlet:
    session:
      tracking-modes: cookie
