spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    com.kakao.cafe.application: info
  file:
    path: logs