spring:
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: flip
    password: flip.chae
    url: jdbc:mysql://mysql_database:3306/kakaodb?serverTimezone=UTC

  sql:
    init:
      mode: always

server:
  servlet:
    session:
      tracking-modes: cookie
