server:
  port: 8082

handlebars:
  suffix: .hbs
  cache: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: errors
  mvc:
    hiddenmethod:
      filter:
        enabled: true
