server:
  port: 8082

handlebars:
  suffix: .hbs
  cache: false
  expose-session-attributes: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: errors
  mvc:
    hiddenmethod:
      filter:
        enabled: true
