spring.config.import: vault://secret/kina-spring-cafe/secret/kina/dev
spring.cloud.vault:
  authentication: APPROLE
  app-role.role-id: 481f6139-aa3a-7863-4cca-7ab76844b3de
  app-role.secret-id: cf4a88b5-fa6e-f578-f602-fcbac4e340fb
  host: vault-beta.daumkakao.io
  port: 443
  scheme: https
  fail-fast: true
  enabled: true

# DB
spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}
  mustache:
    cache: false
    expose-session-attributes: true
  handlebars:
    suffix: .html
    cache: false
  profiles:
    active: mysql-secret

logging.level.com.kakao.cafe: debug
