spring:
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
      driverClassName: org.h2.Driver
      username: sa
      password:
  h2.console:
    enabled: true
    path: /h2-console
#    jdbc:h2:mem:kakaodb
