spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      tracking-modes: cookie
