server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  profiles:
    active: h2
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
