spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/kakaodb
  sql:
    init:
      schema-locations: classpath:script.sql
      mode: always
