spring:
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
server:
  servlet:
    session:
      tracking-modes: cookie
