spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb
  sql:
    init:
      schema-locations: classpath:script.sql
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console