spring:
  mustache:
    cache: false
    suffix: .html
  datasource:
      driverClassName: org.h2.Driver
      username: sa
      password:
  h2.console:
    enabled: true
    path: /h2-console
#    jdbc:h2:mem:kakaodb
