server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  mustache:
    cache: false
    suffix: .html
    expose-session-attributes: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kakaodb
    username: sa
    password: 
    
  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
