spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: low103654est
server:
  servlet:
    session:
      tracking-modes: cookie