spring:
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: hello
    password: world
  sql:
    init:
      schema-locations: classpath:mysql/schema.sql
      data-locations: classpath:mysql/data.sql

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    com.kakao.cafe.application: info
  file:
    path: logs