spring:
  profiles:
    group:
      "local": "localdb, common"
      "test": "testdb, common"
---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:kakaodb
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

---

spring:
  config:
    activate:
      on-profile: "common"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mustache:
    cache: false
    expose-session-attributes: true
