DROP TABLE IF EXISTS USERLIST;
CREATE TABLE IF NOT EXISTS USERLIST
(
    ID       LONG PRIMARY KEY auto_increment,
    USERID   VARCHAR(255),
    PASSWORD VARCHAR(255),
    NAME     VARCHAR(255),
    EMAIL    VARCHAR(255)
);

DROP TABLE IF EXISTS ARTICLE;
CREATE TABLE IF NOT EXISTS ARTICLE
(
    ID        LONG PRIMARY KEY auto_increment,
    WRITETIME VARCHAR(255),
    WRITER    VARCHAR(255),
    TITLE     VARCHAR(255),
    CONTENTS  VARCHAR(255)
);
