CREATE TABLE IF NOT EXISTS USERS
(
    user_seq_id      BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    article_seq_id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    writer_id VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    contents VARCHAR NOT NULL
);