INSERT INTO USER_TABLE VALUES ( 'FIRSTID', '1234', 'NAME1', 'ABC@GMAIL.COM' ),
                              ( 'SECONDID', '1234', 'NAME2', 'EFD@GMAIL.COM' );

INSERT INTO ARTICLE_TABLE (TITLE, CONTENT, USERID) VALUES ('TITLE1', 'WRITE CONTENT HERE111', 'FIRSTID' );
INSERT INTO ARTICLE_TABLE (TITLE, CONTENT, USERID) VALUES ('TITLE2', 'WRITE CONTENT HERE222', 'SECONDID' );

INSERT INTO REPLY_TABLE(USERID, ARTICLEID, CONTENT) VALUES ( 'FIRSTID', 1, 'REPLY CONTENT TEST1111' );
INSERT INTO REPLY_TABLE(USERID, ARTICLEID, CONTENT) VALUES ( 'SECONDID', 1, 'REPLY CONTENT TEST22222' );