SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE IF NOT EXISTS USERS
(
    ID       BIGINT AUTO_INCREMENT,
    USER_ID  VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(20)        NOT NULL,
    NAME     VARCHAR(20)        NOT NULL,
    EMAIL    VARCHAR(50)        NOT NULL,
    PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS ARTICLES CASCADE;

CREATE TABLE IF NOT EXISTS ARTICLES
(
    ARTICLE_ID   BIGINT AUTO_INCREMENT,
    TITLE        VARCHAR(200) NOT NULL,
    WRITER_ID    VARCHAR(20)  NOT NULL,
    CONTENT      VARCHAR(500),
    CREATED_DATE TIMESTAMP    NOT NULL,
    IS_DELETED      BOOLEAN      NOT NULL,
    FOREIGN KEY (WRITER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (ARTICLE_ID)
);
DROP TABLE IF EXISTS COMMENTS CASCADE;

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ARTICLE_ID   BIGINT      NOT NULL,
    COMMENT_ID   BIGINT AUTO_INCREMENT,
    WRITER_ID    VARCHAR(20) NOT NULL,
    CONTENT      VARCHAR(500),
    CREATED_DATE TIMESTAMP   NOT NULL,
    IS_DELETED      BOOLEAN      NOT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ARTICLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (WRITER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (COMMENT_ID)
);

SET FOREIGN_KEY_CHECKS = 1;