CREATE TABLE `USER`
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID  VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME     VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL
);

CREATE TABLE `ARTICLE`
(
    ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE   VARCHAR(255)  NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL
);
