DROP TABLE IF EXISTS USER_TABLE;
DROP TABLE If EXISTS ARTICLE_TABLE;
CREATE TABLE IF NOT EXISTS USER_TABLE (USERID VARCHAR (32), PASSWORD VARCHAR (32), NAME VARCHAR (32), EMAIL VARCHAR (32));
CREATE TABLE If NOT EXISTS ARTICLE_TABLE (ID INT PRIMARY KEY AUTO_INCREMENT, TITLE VARCHAR(32), CONTENT VARCHAR(200));
