package com.kakao.cafe.repository.article;

import com.kakao.cafe.entity.ArticleEntity;

import java.util.ArrayList;
import java.util.List;

public class ArticleMemoryRepository implements ArticleRepository{
    private final List<ArticleEntity> articleMemoryDatabase = new ArrayList<>();

    @Override
    public <S extends ArticleEntity> S save(S entity) {
        entity.putArticleId(getAutoGeneratedKey());
        entity.initDate();

        articleMemoryDatabase.add(entity);
        return entity;
    }

    private Long getAutoGeneratedKey() {
        return Long.valueOf(articleMemoryDatabase.size());
    }

    @Override
    public ArticleEntity findOne(Long primaryKey) {
        return articleMemoryDatabase.stream()
                .filter(u -> u.getId().equals(primaryKey))
                .findFirst()
                .orElseThrow();
    }

    @Override
    public List<ArticleEntity> findAll() {
        return articleMemoryDatabase;
    }

    @Override
    public Long count() {
        return Long.valueOf(articleMemoryDatabase.size());
    }

    @Override
    public void delete(ArticleEntity entity) {
        articleMemoryDatabase.remove(entity);
    }

    @Override
    public boolean exists(Long primaryKey) {
        return articleMemoryDatabase.stream()
                .filter(u -> u.getId().equals(primaryKey))
                .findFirst()
                .isPresent();
    }
}
