package com.kakao.cafe.domain;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import lombok.Getter;

@Getter
public class ArticleBoard {

  public static int DEFAULT_PAGE_INDEX_SIZE = 5;
  public static int DEFAULT_PAGE_SIZE = 10;
  public static int MINIMUM_PAGE_SIZE = 1;
  public static int FIRST_PAGE_INDEX = 1;
  private final int totalArticleSize;
  private ArticlePage articlePage;
  private final int currentPageIndex;
  private final int articlesPerPage;
  private final int pageIndexSize;


  private ArticleBoard(
      int totalArticleSize, ArticlePage articlePage,
      int currentPageIndex, int articlesPerPage, int pageIndexSize
  ) {
    this.totalArticleSize = totalArticleSize;
    this.articlePage = articlePage;
    this.currentPageIndex = currentPageIndex;
    this.articlesPerPage = articlesPerPage;
    this.pageIndexSize = pageIndexSize;
    checkValidation();
  }


  /**
   * 전체 게시물 개수와 현재 페이지 번호를 받아 빈 게시판 생성
   *
   * @param totalArticleSize 전체 게시물 개수
   * @param currentPageIndex 현재 페이지 번호
   * @return ArticleBoard
   */
  public static ArticleBoard createEmpty(
      int totalArticleSize, int currentPageIndex
  ) {
    return new ArticleBoard(
        totalArticleSize,
        null,
        currentPageIndex,
        DEFAULT_PAGE_SIZE,
        DEFAULT_PAGE_INDEX_SIZE
    );
  }


  /**
   * 현재 게시판의 페이지네이션을 계산하여 객체로 반환
   *
   * @return List<Pagination>
   */
  public List<Pagination> getPagination() {

    int min = getMinIndex();
    int max = getMaxIndex();

    return IntStream.rangeClosed(min, max)
        .mapToObj(index -> {
          boolean isCurrent = currentPageIndex == index;
          return new Pagination(index, isCurrent);
        })
        .collect(Collectors.toList());
  }


  /**
   * 현재 페이지네이션에서 Next 활성화 여부 반환
   *
   * @return Next 활성화 여부
   */
  public boolean isNextOn() {
    return getMaxIndex() != getLastPageIndex();
  }


  /**
   * 현재 페이지네이션에서 Previous 활성화 여부 반환
   *
   * @return Previous 활성화 여부
   */
  public boolean isPreviousOn() {
    return getMinIndex() != FIRST_PAGE_INDEX;
  }


  /**
   * 현재 게시판에서 Next 누를 시 이동하는 페이지 인덱스 계산
   *
   * @return Next 시 페이지 인덱스
   */
  public int getNextIndex() {
    return Math.min(getMaxIndex() + 1, getLastPageIndex());
  }


  /**
   * 현재 게시판에서 Previous 누를 시 이동하는 페이지 인덱스 계산
   *
   * @return Previous 시 페이지 인덱스
   */
  public int getPreviousIndex() {
    return Math.max(getMinIndex() - 1, FIRST_PAGE_INDEX);
  }


  /**
   * 현재 게시판의 offset 계산
   *
   * @return offset
   */
  public int offset() {
    return (currentPageIndex - 1) * articlesPerPage;
  }


  /**
   * 현재 게시판의 게시글 목록 세팅
   *
   * @param articlePage 게시글 목록
   */
  public void setArticlePage(ArticlePage articlePage) {
    this.articlePage = articlePage;
  }


  /**
   * auto-generated by intellij
   *
   * @return string for log
   */
  @Override
  public String toString() {
    return "ArticleBoard{" +
        "totalArticleSize=" + totalArticleSize +
        ", articlePage=" + articlePage +
        ", currentPageIndex=" + currentPageIndex +
        ", articlesPerPage=" + articlesPerPage +
        '}';
  }


  private void checkValidation() {

    if (currentPageIndex < FIRST_PAGE_INDEX ||
        articlesPerPage < MINIMUM_PAGE_SIZE) {
      // TODO: need customizing
      throw new RuntimeException();
    }

    if (currentPageIndex > getLastPageIndex()) {
      // TODO: need customizing
      throw new RuntimeException();
    }

  }


  private int getMinIndex() {
    return ((currentPageIndex - 1) / pageIndexSize) * pageIndexSize + 1;
  }


  private int getMaxIndex() {
    int maxIndex = (((currentPageIndex - 1) / pageIndexSize) + 1) * pageIndexSize;
    return Math.min(maxIndex, getLastPageIndex());
  }


  private int getLastPageIndex() {
    if (totalArticleSize == 0) {
      return FIRST_PAGE_INDEX;
    }

    if (totalArticleSize % articlesPerPage == 0) {
      return totalArticleSize / articlesPerPage;
    }

    return totalArticleSize / articlesPerPage + 1;
  }


  @Getter
  public static class Pagination {

    private int index;
    private boolean isCurrent;

    private Pagination(int index, boolean isCurrent) {
      this.index = index;
      this.isCurrent = isCurrent;
    }


    /**
     * 페이지네이션 객체 생성하여 반환
     *
     * @param index     페이지 번호
     * @param isCurrent 현재 페이지 여부
     * @return Pagination
     */
    public static Pagination of(int index, boolean isCurrent) {
      return new Pagination(index, isCurrent);
    }


    /**
     * auto-generated by intellij
     *
     * @return string for log
     */
    @Override
    public String toString() {
      return "Pagination{" +
          "index=" + index +
          ", isCurrent=" + isCurrent +
          '}';
    }

  }

}
