package com.kakao.cafe.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import lombok.Getter;

@Getter
public class ArticlePage {

  private final List<Article> articles;

  private ArticlePage(List<Article> articles) {
    int size = ArticleBoard.DEFAULT_PAGE_SIZE;
    this.articles = Optional.ofNullable(articles)
        .orElseGet(() -> new ArrayList<>(size));
  }


  /**
   * 게시물 페이지 객체 생성
   *
   * @param articles 게시물 리스트
   * @return ArticlePage
   */
  public static ArticlePage of(List<Article> articles) {
    return new ArticlePage(articles);
  }


  /**
   * auto-generated by intellij
   *
   * @return string for log
   */
  @Override
  public String toString() {
    return "ArticlePage{" +
        "articles=" + articles +
        '}';
  }

}
