package com.kakao.cafe.domain;

import com.kakao.cafe.exception.EmailFormatException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.Getter;
import org.apache.commons.lang3.StringUtils;

@Getter
public class Email {

  private static final String regex = "^(.+)@(.+)$";
  private String fullPath;

  private Email(String fullPath) {

    if (StringUtils.isBlank(fullPath) ||
        isNotEmail(fullPath)) {
      throw new EmailFormatException();
    }

    this.fullPath = fullPath;
  }


  /**
   * 이메일 주소를 받아 이메일 양식 검토 후 객체 생성
   *
   * @param fullPath 이메일 주소
   * @return Email
   * @throws EmailFormatException 이메일 양식 오류
   */
  public static Email of(String fullPath) {
    return new Email(fullPath);
  }


  /**
   * auto-generated by intellij
   *
   * @return string for log
   */
  @Override
  public String toString() {
    return fullPath;
  }


  private boolean isNotEmail(String path) {
    Pattern pattern = Pattern.compile(regex);
    Matcher matcher = pattern.matcher(path);
    return !matcher.matches();
  }

}
