package com.kakao.cafe.domain;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;

public class Users implements Iterable<User> {

  private final List<User> users;

  private Users() {
    users = new ArrayList<>();
  }


  private Users(List<User> users) {
    this.users = users;
  }


  /**
   * List 타입을 1급 컬렉션 타입으로 초기화
   *
   * @param users List<User>
   * @return Users
   */
  public static Users of(List<User> users) {
    return new Users(users);
  }


  /**
   * override Iterable
   *
   * @return Iterator<User>
   */
  @Override
  public Iterator<User> iterator() {
    return users.iterator();
  }


  /**
   * override Iterable
   *
   * @param action action in each loop
   */
  @Override
  public void forEach(Consumer<? super User> action) {
    users.forEach(action);
  }


  /**
   * auto-generated by intellij
   *
   * @return string for log
   */
  @Override
  public String toString() {
    return "Users{" +
        "users=" + users +
        '}';
  }


  /**
   * for using stream
   *
   * @return Stream<User>
   */
  public Stream<User> stream() {
    return users.stream();
  }

}
