CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    author_id BIGINT NOT NULL,
    title VARCHAR(50) NOT NULL,
    contents BLOB,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    view_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    status BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(author_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPLY (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    article_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    comment BLOB,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(article_id) REFERENCES ARTICLE(id) ON DELETE CASCADE,
    FOREIGN KEY(author_id) REFERENCES USERS(id) ON DELETE CASCADE
);