CREATE TABLE IF NOT EXISTS USER (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    uid VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(15) NOT NULL,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    uid VARCHAR(15) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY(uid) REFERENCES USER(uid) ON DELETE CASCADE
);
