DROP TABLE users if EXISTS;
CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255),
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    created_time TIMESTAMP,
    PRIMARY KEY(id)
);


DROP TABLE articles IF EXISTS;
CREATE TABLE articles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    writer_name VARCHAR(255),
    title VARCHAR(255),
    contents VARCHAR(255),
    number_of_reply INT,
    created_time TIMESTAMP,
    PRIMARY KEY(id)
);
